version: '2.0'
services:
    web:
        build: .
        command: gunicorn -w 4 -b 0.0.0.0:8000 luizalabs_project:app
        ports:
            - "8000:8000"
        expose:
            - "8000"
        environment: 
            - API_USER=admin
            - API_PASS=admin
            - MONGO_HOST=db
            - MONGO_PORT=27017
        volumes:
            - .:/luizalabs_project
        depends_on:
            - db

    db:
        image: mongo:3.0.2
